# Generated by Django 3.2.12 on 2022-02-27 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_report',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 0, 49, 31, 854882, tzinfo=utc), null=True),
        ),
    ]
