# Generated by Django 3.2.12 on 2022-02-27 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_report_last_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_report',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 27, 0, 34, 28, 966686, tzinfo=utc), null=True),
        ),
    ]
